name: Release

# The workflow will be run when a commit is tagged with a version number
on:
  push:
    tags:
    - 'v*'

env:
  SOLUTION_NAME: lobby-ranks

permissions:
  contents: write
  packages: write

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Clone Repository
      uses: actions/checkout@v4
      with:
        path: plugin
        ref: master
        submodules: recursive

    - name: Clone BakkesmodSDK
      uses: actions/checkout@v4
      with:
        repository: bakkesmodorg/BakkesModSDK
        path: plugin/bakkesmodsdk

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v2

    - name: Build
      run: msbuild /m /p:Configuration=Release /p:BakkesModPath=${{ github.workspace }}/plugin /p:Environment=GitHub ${{ github.workspace }}/plugin/${{ env.SOLUTION_NAME }}.sln

    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        files: plugin/plugins/${{ env.SOLUTION_NAME }}.dll
      env:
        GITHUB_TOKEN: ${{ env.GITHUB_TOKEN }}